// <auto-generated />
namespace SysHotelv1.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class direccion_fieldin_employee_modified : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(direccion_fieldin_employee_modified));
        
        string IMigrationMetadata.Id
        {
            get { return "201908110026210_direccion_field-in_employee_modified"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
